/*Each new term in the Fibonacci sequence is generated by
 adding the previous two terms. By starting with 1 and 2,
  the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the
even-valued terms.*/

var fib = 0;
var sum = 0;

for(var i = 1; i < 4000000; i+=fib){
    
    if (fib%2==0){
        sum += fib;    
    }
    if (i%2==0){
        sum += i;
    }
    
    console.log(fib);
    console.log(i);
    
    fib += i;
}

console.log("Sum of even #'s = " + sum);

//Written By Nick Wright